#include <string>

/**
 * @brief Texture vertex shader string
 */
const std::string OGLS_TRS_MVP_TextureV =
    "#version 410 core\n"
    "\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aColor;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "\n"
    "out vec2 TexCoord;\n"
    "\n"
    "// TRS uniforms\n"
    "uniform vec3 uTrans;\n"
    "uniform vec3 uRotate; // degrees\n"
    "uniform vec3 uScale;\n"
    "\n"
    "// Camera matrices\n"
    "uniform mat4 uView;\n"
    "uniform mat4 uProj;\n"
    "\n"
    "mat4 buildModel()\n"
    "{\n"
    "    vec3 rot = radians(uRotate);\n"
    "\n"
    "    // Scale\n"
    "    mat4 S = mat4(1.0);\n"
    "    S[0][0] = uScale.x;\n"
    "    S[1][1] = uScale.y;\n"
    "    S[2][2] = uScale.z;\n"
    "\n"
    "    // Rotation X\n"
    "    float cx = cos(rot.x); float sx = sin(rot.x);\n"
    "    mat4 RX = mat4(1.0);\n"
    "    RX[1][1] = cx;  RX[1][2] = -sx;\n"
    "    RX[2][1] = sx;  RX[2][2] =  cx;\n"
    "\n"
    "    // Rotation Y\n"
    "    float cy = cos(rot.y); float sy = sin(rot.y);\n"
    "    mat4 RY = mat4(1.0);\n"
    "    RY[0][0] = cy;  RY[0][2] = sy;\n"
    "    RY[2][0] = -sy; RY[2][2] = cy;\n"
    "\n"
    "    // Rotation Z\n"
    "    float cz = cos(rot.z); float sz = sin(rot.z);\n"
    "    mat4 RZ = mat4(1.0);\n"
    "    RZ[0][0] = cz; RZ[0][1] = -sz;\n"
    "    RZ[1][0] = sz; RZ[1][1] =  cz;\n"
    "\n"
    "    // Combined rotation\n"
    "    mat4 R = RZ * RY * RX;\n"
    "\n"
    "    // Translation\n"
    "    mat4 T = mat4(1.0);\n"
    "    T[3][0] = uTrans.x;\n"
    "    T[3][1] = uTrans.y;\n"
    "    T[3][2] = uTrans.z;\n"
    "\n"
    "    return T * R * S;\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mat4 model = buildModel();\n"
    "    gl_Position = uProj * uView * model * vec4(aPos, 1.0);\n"
    "    TexCoord = aTexCoord;\n"
    "}\n";

/**
 * @brief Texture fragment shader string
 */
const std::string OGLS_TRS_MVP_TextureF = 
    "#version 410 core\n"
    "in vec2 TexCoord; // Texture coordinates passed from the vertex shader\n"
    "\n"
    "out vec4 FragColor; // Final color output\n"
    "\n"
    "uniform sampler2D ourTexture; // The texture sampler\n"
    "\n"
    "void main()\n"
    "{\n"
    "    FragColor = texture(ourTexture, TexCoord); // Sample the texture at the given coordinates\n"
    "}\n";
