#include "OGLS.hpp"

std::string OGLS_TRS_MVP_ColorV =
    "#version 410 core\n"
    "\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aColor;\n"
    "\n"
    "// TRS uniforms\n"
    "uniform vec3 uTrans;\n"
    "uniform vec3 uRotate; // degrees\n"
    "uniform vec3 uScale;\n"
    "\n"
    "// Camera matrices\n"
    "uniform mat4 uView;\n"
    "uniform mat4 uProj;\n"
    "\n"
    "mat4 buildModel()\n"
    "{\n"
    "    vec3 rot = radians(uRotate);\n"
    "\n"
    "    // Scale\n"
    "    mat4 S = mat4(1.0);\n"
    "    S[0][0] = uScale.x;\n"
    "    S[1][1] = uScale.y;\n"
    "    S[2][2] = uScale.z;\n"
    "\n"
    "    // Rotation X\n"
    "    float cx = cos(rot.x); float sx = sin(rot.x);\n"
    "    mat4 RX = mat4(1.0);\n"
    "    RX[1][1] = cx;  RX[1][2] = -sx;\n"
    "    RX[2][1] = sx;  RX[2][2] =  cx;\n"
    "\n"
    "    // Rotation Y\n"
    "    float cy = cos(rot.y); float sy = sin(rot.y);\n"
    "    mat4 RY = mat4(1.0);\n"
    "    RY[0][0] = cy;  RY[0][2] = sy;\n"
    "    RY[2][0] = -sy; RY[2][2] = cy;\n"
    "\n"
    "    // Rotation Z\n"
    "    float cz = cos(rot.z); float sz = sin(rot.z);\n"
    "    mat4 RZ = mat4(1.0);\n"
    "    RZ[0][0] = cz; RZ[0][1] = -sz;\n"
    "    RZ[1][0] = sz; RZ[1][1] =  cz;\n"
    "\n"
    "    // Combined rotation\n"
    "    mat4 R = RZ * RY * RX;\n"
    "\n"
    "    // Translation\n"
    "    mat4 T = mat4(1.0);\n"
    "    T[3][0] = uTrans.x;\n"
    "    T[3][1] = uTrans.y;\n"
    "    T[3][2] = uTrans.z;\n"
    "\n"
    "    return T * R * S;\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mat4 model = buildModel();\n"
    "    gl_Position = uProj * uView * model * vec4(aPos, 1.0);\n"
    "}\n";

std::string OGLS_TRS_MVP_ColorF = 
    "#version 410 core\n"
    "\n"
    "uniform vec4 uColor;\n"
    "out vec4 FragColor; // Final color output\n"
    "\n"
    "void main()\n"
    "{\n"
    "    FragColor = uColor;\n"
    "}\n";

//--------------------------------------------------------------------------------------------------------------------------------------------------------

std::string OGLS_TRS_MVP_TextureV =
    "#version 410 core\n"
    "\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aColor;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "\n"
    "out vec2 TexCoord;\n"
    "\n"
    "// TRS uniforms\n"
    "uniform vec3 uTrans;\n"
    "uniform vec3 uRotate; // degrees\n"
    "uniform vec3 uScale;\n"
    "\n"
    "// Camera matrices\n"
    "uniform mat4 uView;\n"
    "uniform mat4 uProj;\n"
    "\n"
    "mat4 buildModel()\n"
    "{\n"
    "    vec3 rot = radians(uRotate);\n"
    "\n"
    "    // Scale\n"
    "    mat4 S = mat4(1.0);\n"
    "    S[0][0] = uScale.x;\n"
    "    S[1][1] = uScale.y;\n"
    "    S[2][2] = uScale.z;\n"
    "\n"
    "    // Rotation X\n"
    "    float cx = cos(rot.x); float sx = sin(rot.x);\n"
    "    mat4 RX = mat4(1.0);\n"
    "    RX[1][1] = cx;  RX[1][2] = -sx;\n"
    "    RX[2][1] = sx;  RX[2][2] =  cx;\n"
    "\n"
    "    // Rotation Y\n"
    "    float cy = cos(rot.y); float sy = sin(rot.y);\n"
    "    mat4 RY = mat4(1.0);\n"
    "    RY[0][0] = cy;  RY[0][2] = sy;\n"
    "    RY[2][0] = -sy; RY[2][2] = cy;\n"
    "\n"
    "    // Rotation Z\n"
    "    float cz = cos(rot.z); float sz = sin(rot.z);\n"
    "    mat4 RZ = mat4(1.0);\n"
    "    RZ[0][0] = cz; RZ[0][1] = -sz;\n"
    "    RZ[1][0] = sz; RZ[1][1] =  cz;\n"
    "\n"
    "    // Combined rotation\n"
    "    mat4 R = RZ * RY * RX;\n"
    "\n"
    "    // Translation\n"
    "    mat4 T = mat4(1.0);\n"
    "    T[3][0] = uTrans.x;\n"
    "    T[3][1] = uTrans.y;\n"
    "    T[3][2] = uTrans.z;\n"
    "\n"
    "    return T * R * S;\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mat4 model = buildModel();\n"
    "    gl_Position = uProj * uView * model * vec4(aPos, 1.0);\n"
    "    TexCoord = aTexCoord;\n"
    "}\n";

std::string OGLS_TRS_MVP_TextureF = 
    "#version 410 core\n"
    "in vec2 TexCoord; // Texture coordinates passed from the vertex shader\n"
    "\n"
    "out vec4 FragColor; // Final color output\n"
    "\n"
    "uniform sampler2D ourTexture; // The texture sampler\n"
    "\n"
    "void main()\n"
    "{\n"
    "    FragColor = texture(ourTexture, 1.0 - TexCoord); // Sample the texture at the given coordinates\n"
    "}\n";

//--------------------------------------------------------------------------------------------------------------------------------------------------------

std::string OGLS_ROOT_OBJ_V =
    "#version 410 core\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);\n"
    "}\n";

std::string OGLS_ROOT_OBJ_F =
    "#version 410 core\n"
    "\n"
    "out vec4 FragColor; // Final color output\n"
    "\n"
    "void main()\n"
    "{\n"
    "    FragColor = vec4(1.0, 1.0, 1.0, 0.0); // Sample the texture at the given coordinates\n"
    "}\n";

//--------------------------------------------------------------------------------------------------------------------------------------------------------

std::string OGLS_TRS_MVP_Lit_Blinn_Phong_TextureV =
    "#version 410 core\n"
    "\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aColor;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "layout (location = 3) in vec3 aNormal;\n"
    "\n"
    "out vec2 TexCoord;\n"
    "out vec3 FragPos; // Position in world space\n"
    "out vec3 Normal;  // Normal in world space\n"
    "\n"
    "// TRS uniforms\n"
    "uniform vec3 uTrans;\n"
    "uniform vec3 uRotate; // degrees\n"
    "uniform vec3 uScale;\n"
    "\n"
    "// Camera matrices\n"
    "uniform mat4 uView;\n"
    "uniform mat4 uProj;\n"
    "\n"
    "mat4 buildModel()\n"
    "{\n"
    "    vec3 rot = radians(uRotate);\n"
    "\n"
    "    // Scale\n"
    "    mat4 S = mat4(1.0);\n"
    "    S[0][0] = uScale.x;\n"
    "    S[1][1] = uScale.y;\n"
    "    S[2][2] = uScale.z;\n"
    "\n"
    "    // Rotation X\n"
    "    float cx = cos(rot.x); float sx = sin(rot.x);\n"
    "    mat4 RX = mat4(1.0);\n"
    "    RX[1][1] = cx;  RX[1][2] = -sx;\n"
    "    RX[2][1] = sx;  RX[2][2] =  cx;\n"
    "\n"
    "    // Rotation Y\n"
    "    float cy = cos(rot.y); float sy = sin(rot.y);\n"
    "    mat4 RY = mat4(1.0);\n"
    "    RY[0][0] = cy;  RY[0][2] = sy;\n"
    "    RY[2][0] = -sy; RY[2][2] = cy;\n"
    "\n"
    "    // Rotation Z\n"
    "    float cz = cos(rot.z); float sz = sin(rot.z);\n"
    "    mat4 RZ = mat4(1.0);\n"
    "    RZ[0][0] = cz; RZ[0][1] = -sz;\n"
    "    RZ[1][0] = sz; RZ[1][1] =  cz;\n"
    "\n"
    "    // Combined rotation\n"
    "    mat4 R = RZ * RY * RX;\n"
    "\n"
    "    // Translation\n"
    "    mat4 T = mat4(1.0);\n"
    "    T[3][0] = uTrans.x;\n"
    "    T[3][1] = uTrans.y;\n"
    "    T[3][2] = uTrans.z;\n"
    "\n"
    "    return T * R * S;\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mat4 model = buildModel();\n"
    "    gl_Position = uProj * uView * model * vec4(aPos, 1.0);\n"
    "    FragPos = vec3(model * vec4(aPos, 1.0));\n"
    "    Normal = mat3(transpose(inverse(model))) * aNormal; // Transform normal correctly \n"
    "    TexCoord = aTexCoord;\n"
    "}\n";

std::string OGLS_TRS_MVP_Lit_Blinn_Phong_TextureF =
    "#version 410 core\n"
    "\n"
    "in vec2 TexCoord;\n"
    "in vec3 FragPos;\n"
    "in vec3 Normal;\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    // Light
    "uniform vec3 uLightDir;\n"
    "uniform vec3 uLightColor;\n"
    "uniform float uLightIntensity;\n"
    // Material
    "uniform vec3 uMatAmbientColor;\n"
    "uniform vec3 uMatDiffuseColor;\n"
    "uniform vec3 uMatSpecularColor;\n"
    "uniform vec3 uMatEmitColor;\n"
    "uniform float uMatEmitIntensity;\n"
    "uniform float uMatShininess;\n"
    "\n"
    "uniform sampler2D ourTexture;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec3 norm = normalize(Normal);\n"
    "    vec3 lightDir = normalize(-uLightDir);\n"
    "    \n"
    "    // Diffuse lighting\n"
    "    float diff = max(dot(norm, lightDir), 0.0);\n"
    "\n"
    "    // Specular lighting (Blinn-Phong)\n"
    "    vec3 viewDir = normalize(-FragPos); // Assuming camera at origin\n"
    "    vec3 halfwayDir = normalize(lightDir + viewDir);\n"
    "    float spec = pow(max(dot(norm, halfwayDir), 0.0), uMatShininess);\n"
    "\n"
    "    // Texture\n"
    "    vec3 texColor = texture(ourTexture, 1.0 - TexCoord).rgb;\n"
    "\n"
    "    // Combine material, texture, and lighting\n"
    "    vec3 ambient = uMatAmbientColor * texColor;\n"
    "    vec3 diffuse = uMatDiffuseColor * diff * texColor;\n"
    "    vec3 specular = uMatSpecularColor * spec;\n"
    "    vec3 emissive = uMatEmitColor * uMatEmitIntensity;\n"
    "\n"
    "    vec3 result = (ambient + diffuse + specular + emissive) * uLightIntensity;\n"
    "    result *= uLightColor; // multiply by light color\n"
    "\n"
    "    FragColor = vec4(result, 1.0);\n"
    "}\n";

//--------------------------------------------------------------------------------------------------------------------------------------------------------

std::string OGLS_TRS_MVP_Lit_Blinn_Phong_Texture_AttenuatedV =
    "#version 410 core\n"
    "\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aColor;\n"
    "layout (location = 2) in vec2 aTexCoord;\n"
    "layout (location = 3) in vec3 aNormal;\n"
    "\n"
    "out vec2 TexCoord;\n"
    "out vec3 FragPos; // Position in world space\n"
    "out vec3 Normal;  // Normal in world space\n"
    "\n"
    "// TRS uniforms\n"
    "uniform vec3 uTrans;\n"
    "uniform vec3 uRotate; // degrees\n"
    "uniform vec3 uScale;\n"
    "\n"
    "// Camera matrices\n"
    "uniform mat4 uView;\n"
    "uniform mat4 uProj;\n"
    "\n"
    "mat4 buildModel()\n"
    "{\n"
    "    vec3 rot = radians(uRotate);\n"
    "\n"
    "    // Scale\n"
    "    mat4 S = mat4(1.0);\n"
    "    S[0][0] = uScale.x;\n"
    "    S[1][1] = uScale.y;\n"
    "    S[2][2] = uScale.z;\n"
    "\n"
    "    // Rotation X\n"
    "    float cx = cos(rot.x); float sx = sin(rot.x);\n"
    "    mat4 RX = mat4(1.0);\n"
    "    RX[1][1] = cx;  RX[1][2] = -sx;\n"
    "    RX[2][1] = sx;  RX[2][2] =  cx;\n"
    "\n"
    "    // Rotation Y\n"
    "    float cy = cos(rot.y); float sy = sin(rot.y);\n"
    "    mat4 RY = mat4(1.0);\n"
    "    RY[0][0] = cy;  RY[0][2] = sy;\n"
    "    RY[2][0] = -sy; RY[2][2] = cy;\n"
    "\n"
    "    // Rotation Z\n"
    "    float cz = cos(rot.z); float sz = sin(rot.z);\n"
    "    mat4 RZ = mat4(1.0);\n"
    "    RZ[0][0] = cz; RZ[0][1] = -sz;\n"
    "    RZ[1][0] = sz; RZ[1][1] =  cz;\n"
    "\n"
    "    // Combined rotation\n"
    "    mat4 R = RZ * RY * RX;\n"
    "\n"
    "    // Translation\n"
    "    mat4 T = mat4(1.0);\n"
    "    T[3][0] = uTrans.x;\n"
    "    T[3][1] = uTrans.y;\n"
    "    T[3][2] = uTrans.z;\n"
    "\n"
    "    return T * R * S;\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mat4 model = buildModel();\n"
    "    gl_Position = uProj * uView * model * vec4(aPos, 1.0);\n"
    "    FragPos = vec3(model * vec4(aPos, 1.0));\n"
    "    Normal = mat3(transpose(inverse(model))) * aNormal; // Transform normal correctly \n"
    "    TexCoord = aTexCoord;\n"
    "}\n";

std::string OGLS_TRS_MVP_Lit_Blinn_Phong_Texture_AttenuatedF =
    "#version 410 core\n"
    "\n"
    "in vec2 TexCoord;\n"
    "in vec3 FragPos;\n"
    "in vec3 Normal;\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    // Light
    "uniform vec3 uLightDir;\n"             // Point light, not directional!
    "uniform vec3 uLightColor;\n"
    "uniform float uLightIntensity;\n"
    // Material
    "uniform vec3 uMatAmbientColor;\n"
    "uniform vec3 uMatDiffuseColor;\n"
    "uniform vec3 uMatSpecularColor;\n"
    "uniform vec3 uMatEmitColor;\n"
    "uniform float uMatEmitIntensity;\n"
    "uniform float uMatShininess;\n"
    "\n"
    "uniform sampler2D ourTexture;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec3 norm = normalize(Normal);\n"
    "    vec3 lightDir = uLightDir - FragPos;\n"
    "    float distance = length(lightDir);\n"
    "    lightDir = normalize(lightDir);\n"
    "\n"
    "    // Attenuation (classic quadratic)\n"
    "    float attenuation = 1.0 / (distance * distance);\n"
    "\n"
    "    // Diffuse lighting\n"
    "    float diff = max(dot(norm, lightDir), 0.0);\n"
    "\n"
    "    // Specular lighting (Blinn-Phong)\n"
    "    vec3 viewDir = normalize(-FragPos); // camera at origin\n"
    "    vec3 halfwayDir = normalize(lightDir + viewDir);\n"
    "    float spec = pow(max(dot(norm, halfwayDir), 0.0), uMatShininess);\n"
    "\n"
    "    // Texture\n"
    "    vec3 texColor = texture(ourTexture, 1.0 - TexCoord).rgb;\n"
    "\n"
    "    // Combine material, texture, and lighting\n"
    "    vec3 ambient = uMatAmbientColor * texColor;\n"
    "    vec3 diffuse = uMatDiffuseColor * diff * texColor;\n"
    "    vec3 specular = uMatSpecularColor * spec;\n"
    "    vec3 emissive = uMatEmitColor * uMatEmitIntensity;\n"
    "\n"
    "    vec3 result = (ambient + diffuse + specular + emissive) * uLightIntensity * attenuation;\n"
    "    result *= uLightColor;\n"
    "\n"
    "    FragColor = vec4(result, 1.0);\n"
    "}\n";

//--------------------------------------------------------------------------------------------------------------------------------------------------------


std::string OGLS_GlyphV = R"(
    #version 330 core
    layout (location = 0) in vec4 vertex; // <vec2 pos, vec2 tex>
    out vec2 TexCoords;

    uniform mat4 projection;

    void main()
    {
        gl_Position = projection * vec4(vertex.xy, 0.0, 1.0);
        TexCoords = vertex.zw;
    }
)";

std::string OGLS_GlyphF = R"(
    #version 330 core
    in vec2 TexCoords;
    out vec4 color;

    uniform sampler2D text;
    uniform vec3 textColor;

    void main()
    {    
        vec4 sampled = vec4(1.0, 1.0, 1.0, texture(text, TexCoords).r);
        color = vec4(textColor, 1.0) * sampled;
    }  
)";